### ISSUE TITLE
[Grid] (Chrome) On media queries, gutter is collapsing in unexpected manner

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#502] opened 2015-09-11 19:40 UTC
See video for illustration:

http://screencast-o-matic.com/watch/coQXYIfHNn

Desired gutter = remains atleast 30px (or em equivalent) across media queries.

Note: revisit this bug after content is loaded into the site.

**Comment by maya** [comment] 2015-09-11 20:02
@mollieru the gutters are 30px

<img width="960" alt="screen shot 2015-09-11 at 1 01 33 pm" src="https://cloud.githubusercontent.com/assets/5249443/9824971/4aaa990c-5885-11e5-85d7-0d1c24a013d1.png">

**Comment by mollieru** [comment] 2015-09-11 20:14
http://screencast-o-matic.com/watch/coQXYIfHNn

**Comment by carodew** [comment] 2015-09-11 20:25
FWIW, this is what I see with borders on the two containers: http://g.recordit.co/gPo2DnMkPu.gif

**Comment by maya** [comment] 2015-09-11 20:41
By default, Neat calculates gutters based upon the golden ratio and uses modular scale.

`$gutter: modular-scale(1, 1em, $golden) !default;`

http://thoughtbot.github.io/neat-docs/latest/#gutter

**Comment by maya** [comment] 2015-09-11 20:41
but the site margins are 30px.

**Comment by carodew** [comment] 2015-09-14 20:06
Just for the sake of not forgetting, @mollieru is going to post an example of this with real text instead of dummy text.

**Comment by wardpenney** [comment] 2015-10-22 21:43
From an email chain:

For the gutter, the value you set on $gutter is only used to calculate the relative width of gutters to columns ($column). So ultimately setting it to 30px will just result in a different ratio if $column is defined in px as well.

This is by design, since having fixed gutters would require relying on calc() and is not compatible with Neat's interpretation of a fluid grid.

**Comment by carodew** [comment] 2016-03-17 17:45
Closing this issue since this is behaving as expected.

**Closed by carodew** 2016-03-17 17:45 UTC
Labels: bug, frontend, low, more information needed
