### ISSUE TITLE
[Homepage] Screenshots are not full width

### ISSUE THREAD

**Issue by KHarshawat** [18F/web-design-standards#548] opened 2015-09-15 20:31 UTC
In the section examples section, the screenshots pulled out are not aligned with the `View the standards` button below. Consider growing the screenshots to the width of the container or centering the `View the standards` button.

![image](https://cloud.githubusercontent.com/assets/6335546/9888609/08bd54fc-5bc4-11e5-839a-4bc5a95c9faf.png)

**Comment by maya** [comment] 2015-09-15 22:42
This was by design I believe.

**Comment by angel** [comment] 2015-09-15 22:52
@maya is right, that's how it was designed. I think full width would be too big on the page for each screenshot, but maybe there's another solution that would take up the whole width, like if we had two in each row. Thoughts @KHarshawat @mollieru?

**Comment by angel** [comment] 2015-09-24 05:33
Revisited the examples section of the homepage and decided to update the images to full-width in this PR: https://github.com/18F/web-design-standards/pull/709.

**Comment by maya** [comment] 2015-09-24 17:27
Resolved via #709.

**Closed by maya** 2015-09-24 17:27 UTC
Labels: enhancement, visual design
