### ISSUE TITLE
[Footer] Social media buttons tappable

### ISSUE THREAD

**Issue by JuliaWinn** [18F/web-design-standards#559] opened 2015-09-15 22:11 UTC
When social media buttons are tapped the shadows are not aligned with the images. (slightly below)

**Comment by carodew** [comment] 2015-09-15 22:21
Hi @JuliaWinn Thanks for helping out! This is a duplicate of #347, so I'm closing this issue so we only have one point of reference on it.

**Closed by carodew** 2015-09-15 22:21 UTC
Labels: bug, To be triaged
