### ISSUE TITLE
[Accordians] iPhone 5/Safari: Text in containers lacks right inner margin in some cases

### ISSUE THREAD

**Issue by jjoteal** [18F/web-design-standards#579] opened 2015-09-16 15:13 UTC
*Steps to reproduce*
Open a 'Documentation' accordion on iPhone5/Safari

*Expected behavior*
Right margin between text and accordion border

Screenshot:
![image](https://cloud.githubusercontent.com/assets/12192706/9908925/e25dfcda-5c63-11e5-800e-8f2ac6023fbd.png)

**Comment by mollieru** [comment] 2015-09-16 20:46
@jjoteal what version of iOS are you running?

**Comment by jjoteal** [comment] 2015-09-16 20:50
8.4.1

**Comment by mollieru** [comment] 2015-09-17 20:14
i have 8.3

**Comment by carodew** [comment] 2015-09-17 20:30
I'm able to replicate this using an iPhone 5 simulator, but not on my iPhone 6 (which is also running 8.4.1).

Very strange. 

To simulate: 

1. Open Chrome developer tools:
2. Toggle "Device Mode" to on and select "Apple iPhone 5" from device list. 
3. Navigate to the accordion page and scroll down to the accessibility guidelines. 

You'll see this, which matches the issue above: 

<img width="366" alt="screen shot 2015-09-17 at 4 30 06 pm" src="https://cloud.githubusercontent.com/assets/10144074/9945109/649dbab4-5d59-11e5-8bdb-21c57d67e442.png">

**Comment by carodew** [comment] 2015-09-17 20:36
I think the issue is in the phrase `aria-controls=‘collapsible-#` because the part that says `controls=‘collapsible` does not wrap, which is forcing the entire text area to be wider than it should be.

**Comment by maya** [comment] 2015-09-18 15:25
@carodew are you hitting refresh in the emulator? I did not experience this in emulator or phone for most. I checked every one and only saw this effecting dropdowns.

Also is @jjoteal looking at our most up to date code on staging?

**Comment by carodew** [comment] 2015-09-18 16:09
It's only on iPhone 5 and only on sections where there is a code snippet within the documentation that is not wrapping, and forcing the text block to be wider than the accordion. E.g. on the Accordion Accessibility documentation. I noticed it in a couple other places, which I can list if it's helpful. 

I can verify I did refresh and I am on staging.

**Comment by carodew** [comment] 2015-09-18 16:10
Arguably this could be a medium, but it looks bad so we put it as a high. Happy to revisit during triage.

**Comment by maya** [comment] 2015-09-18 16:12
@carodew I was testing on an iPhone 5

**Comment by jpyuda** [comment] 2015-09-18 19:34
I can't replicate this on an iPhone 5S with 8.4.1

**Comment by carodew** [comment] 2015-09-18 19:41
wbr – word break opportunity might be a fix.

**Comment by maya** [comment] 2015-09-18 21:15
This only happens on text with code snippets, which do not break.

**Comment by carodew** [comment] 2015-09-21 21:22
Just did a quick scan of the entire site, and I only found the issue in two places: 

Accordions (Accessibility)
Dropdowns (Usability / Guidance)

**Comment by maya** [comment] 2015-09-22 03:41
Fixed via #663.

**Closed by maya** 2015-09-22 03:41 UTC
Labels: bug, medium, more information needed
