### ISSUE TITLE
Gulp setup fails...

### ISSUE THREAD

**Issue by jhfrench** [18F/web-design-standards#1128] opened 2016-04-19 01:42 UTC
...on my system with with error "bundle && gulp copy-vendor-sass && gulp build" while attempting to follow the ["Building the project locally with Gulp" instructions](https://github.com/18F/web-design-standards/blob/18f-pages-staging/CONTRIBUTING.md).

Before filing this issue I have:
- [updated my node install](http://stackoverflow.com/a/31520672/1430996) 
- [searched the project's issues for "copy-vendor-sass"](https://github.com/18F/web-design-standards/issues?utf8=%E2%9C%93&q=%22copy-vendor-sass%22) to make sure there isn't already guidance

Selected content from my npm-debug.log:

```
98 error node v5.6.0
99 error npm  v3.8.7
100 error code ELIFECYCLE
101 error uswds@0.9.1 prepublish: `bundle && gulp copy-vendor-sass && gulp build`
101 error Exit status 1
102 error Failed at the uswds@0.9.1 prepublish script 'bundle && gulp copy-vendor-sass && gulp build'.
102 error Make sure you have the latest version of node.js and npm installed.
102 error If you do, this is most likely a problem with the uswds package,
102 error not with npm itself.
102 error Tell the author that this fails on your system:
102 error     bundle && gulp copy-vendor-sass && gulp build
102 error You can get information on how to open an issue for this project with:
102 error     npm bugs uswds
102 error Or if that isn't available, you can get their info via:
102 error     npm owner ls uswds
102 error There is likely additional logging output above.
103 verbose exit [ 1, true ]
```

If you want the whole log file, please let me know how to get it to you (I prefer to not share it here).

**Comment by msecret** [comment] 2016-04-19 18:22
@jhfrench I think it might help to see more output, as I can't find the reason the command failed here.

Another issue currently with our prepublish hook: it requires ruby and bundler to be installed. Could that be the issue?

**Comment by jhfrench** [comment] 2016-04-19 19:18
@msecret I don't already have ruby and bundler installed on my system (if needed, can instructions be added to CONTRIBUTING.md?)...but this particular issue sure looks like it's isolated to the Gulp install/instantiation/[pedantically-correct verb].

I *suspect* that some of the dependencies reference deprecated Gulp package versions, and the above is the result of that.

If you [try a fresh install](https://github.com/18F/web-design-standards/blob/18f-pages-staging/CONTRIBUTING.md) within the latest NPM, does it work for you?

**Comment by madmanlear** [comment] 2016-04-25 19:49
I experienced this same error on a new machine. Installing [Bundler](http://bundler.io/) cleared it right up.

**Comment by joshbruce** [comment] 2016-04-26 13:22
Ran into this error today when doing
```$ gulp website:serve```

website:serve jekyll 3.1.3 | Error: kramdown

Not sure why, given that kramdown is not used - unless it is a dependency for redcarpet.

**Comment by msecret** [comment] 2016-04-28 22:59
I want to keep this issue open to document people having trouble with ruby and bundler being dependencies.

**Comment by maya** [comment] 2016-04-29 20:41
@msecret would it be worth it to include in the installation instructions that you must install Bundler?

**Comment by joshbruce** [comment] 2016-04-29 21:46
@maya and @msecret: For the extension I'm working on for my program, this is the current CONTRIBUTING.md regarding getting set up locally - would this work? 

If so, I will submit a PR. Note: I have not uninstalled everything to test - only set up another teammate who had nothing - also there are links and headers, just not included here.

Note: I could not figure out a way to get the go_script to run the gulp commands; so, we have removed that dependency. Also, while I appreciated the ability to use ```$ npm start```, from a UX perspective I felt having multiple options (gulp, ./go, and npm) could confuse novices. But, this whole note is more a different issue all together, I think.

**********************

Building the project locally with gulp

You've cloned the repository. Now, we just have to make sure your environment can do what it needs to in order to serve the site locally.

Start by opening Terminal (OS X) or Command Prompt (Windows).

Confirm Ruby

To serve the site locally, we will need Ruby. Confirm Ruby is installed:

$ gem -v

If you do not see a version number, install RubyGems.

Confirm Ruby Bundler

$ bundle -v

If you do not see a version number, and you have confirmed Ruby:

$ gem install bundler

Confirm NPM

To install the required modules, we will need Node Package Manager (NPM). Confirm NPM is available:

$ npm -v

If you do not see a version number, install Node.js.

Confirm Gulp

To compile the site, we will need Gulp - an NPM module. Confirm Gulp is available:

$ gulp -v

If you do not see a version number, and you have confirmed NPM:

$ npm install --global gulp-cli

Serve the site locally

If you've made it here, you are ready to go. Launch Terminal (OS X) or Command Prompt (Windows) and move to the locally cloned repository.

$ cd ~/path/to/cloned/repo/sam-web-design-standards

Install/Update gems (this could take a moment):

First time: $ bundle install

To update to latest versions: $ bundle update

Update node modules (this could take a moment, especially the first time):

$ npm update

Serve the site:

$ gulp website:serve

After running this command, you should be able to view the Standards website locally (http://127.0.0.1:4000).

This also sets up gulp and Jekyll to watch for file changes; so, as you update files, you should only need to refresh your browser to see the changes. If you do not see the changes, go to Terminal or Command Prompt and see if there were errors during the regeneration.

Note: For a list of available gulp commands use:

$ gulp

**Comment by juliaelman** [comment] 2016-05-20 15:33
@jhfrench we've made some updates to the organization and installation instructions on the `18f-pages-staging` branch. Try checking that out and see if you are still having installation issues.

We're going to close this issue for now, but please feel free to open another issue if you are still having installation problems. The goal is to make this process as painless as possible and your feedback is very valuable in refining these steps!

**Closed by juliaelman** 2016-05-20 15:33 UTC
Labels: [Category] Engineering, [Status] Backlog, [Type] Bug
