### ISSUE TITLE
[Grid Code Example]: Add code snippet for Grid component

### ISSUE THREAD

**Issue by line47** [18F/web-design-standards#2022] opened 2017-07-11 19:23 UTC
## Description

Add a code snippet to the grid component page much like the other components (buttons, tables)

**Comment by donjo** [comment] 2017-07-11 19:54
Reminding myself to do this as part of #2008

**Comment by toolness** [comment] 2017-07-12 11:03
I think this is a duplicate of #1980?  But since this one is already assigned to @donjo I guess I'll go ahead and close #1980 instead.

A funny thing I just discovered is that this *is* actually a regression: I was watching the old USWDS developer-focused tour of the standards from November 2015 and [at 32:22](https://youtu.be/eMIWzj_dPvg?t=32m22s) @maya shows off the grid page, and the example code for the grid is right there. So it got removed at some point!

Hopefully that means that fixing this is as easy as just adding the requisite accordion include, rather than having to write any new example code.

**Closed** 2017-07-17 20:13 UTC
