### ISSUE TITLE
[Side Navigation] When clicking on an anchor tag in the side nav, the resulting scroll position puts the heading at the very top, sometimes cutting off ascenders

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#446] opened 2015-09-08 17:27 UTC
**Steps to recreate**

1. Open the site in IE 11. 
2. Click on Typography to open that section. 
3. Click on Typesetting. 
4. Click on Links. 
5. Notice that the headers for each section (Typesetting, Links) in the main content area are bumping into the main header. 

![ie 11 anchor tags](https://cloud.githubusercontent.com/assets/10144074/9742227/f73e8738-562c-11e5-9312-5bdd24ab3af4.gif)

**Expected behavior**
I would expect some vertical spacing between the section heading in the main content area and the site header. 

**Tested in**
IE 11
Windows 10

**Comment by colinpmacarthur** [comment] 2015-09-09 20:29
When you get to the Name and Address form, the problem is even more extreme.

**Comment by maya** [comment] 2015-09-24 00:19
This was resolved in https://github.com/18F/web-design-standards/pull/496

**Closed by maya** 2015-09-24 00:19 UTC
Labels: bug, low
