### ISSUE TITLE
[Refactor HTML/CSS] Ensure all uses of ems over rems make sense

### ISSUE THREAD

**Issue by juliaelman** [18F/web-design-standards#1426] opened 2016-08-30 18:21 UTC
Based off of the larger issue outlined here https://github.com/18F/web-design-standards/issues/1342
- [ ] Scan files for ems/rems usage
- [ ] Determine where we can remove, add or edit these values
- [ ] Implement changes

**Comment by thisisdano** [comment] 2017-10-24 16:29
Duplicate of #992

**Closed by thisisdano** 2017-10-24 16:29 UTC
Labels: [Type] Enhancement, [Type] Maintenance, [Type] Refactor
