### ISSUE TITLE
Scrolling Sticky sidebar partially inaccessible on short and wide viewports

### ISSUE THREAD

**Issue by jpdevries** [18F/web-design-standards#1767] opened 2017-03-04 18:19 UTC
## Description

As a desktop user on an 11" MacBook Air I expect to be able to scroll not only the main content area on the right but also the sidebar on the left. Since the sidebar sticks I cannot scroll to access the parts of the sidebar that fall outside my viewport window until I scroll all the way down the tall content area.

This pattern basically assumes that the user's viewport is taller than the sidebar which sticks, so I think one solution would be to not use position sticky if the viewport is not tall enough.

## Steps to reproduce the issue

1. Browse to https://standards.usa.gov/components/footers/#big-footer in a short viewport (~768px tall)
2. Scroll down
3. Notice sidebar sticks but you can't access all of the sidebar
4. Scroll all the way to the bottom and notice you eventually can access the content

## Additional information [optional]

<details>
<summary>Screenshot (GIF)</summary>
<img src="http://j4p.us/3R0Y1s1v2E11/sticky.gif" alt="Animated GIF showing the described issue" />
</details>

**Comment by juliaelman** [comment] 2017-03-06 15:15
Thank you for opening this issue. The team has added it to our backlog for consideration in our next sprint.

**Comment by juliaelman** [comment] 2017-03-08 21:44
A [duplicate issue](https://github.com/18F/web-design-standards-docs/issues/204) was just opened on our [docs site repo](https://github.com/18F/web-design-standards-docs/). Since the issue is based on our docs site and not an actual Standards component, I am going to close this issue.

Thank you again for opening your issue!

**Closed by juliaelman** 2017-03-08 21:44 UTC
Labels: [Priority] Critical, [Skill] Front end, [Type] Bug
