### ISSUE TITLE
go script problem

### ISSUE THREAD

**Issue by buckaroogeek** [18F/web-design-standards#795] opened 2015-10-06 16:52 UTC
I checked out the web-design-standards repository and tried to run the go script. It failed with the following:  [bgsmith@pico web-design-standards] OOPS! (1) ./go build
  Dependency Error:  Yikes! It looks like you don't have jekyll-coffeescript or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full error message from Ruby is: 'cannot load such file -- json' If you run into trouble, you can find helpful resources at http://jekyllrb.com/help/! 

The solution is found at https://github.com/sdemos/octopress/commit/5ce98bb57982c585f2b4bd8c95ec327de0e3a108. That is, add `gem 'json'` to the Gemfile. 

This is  all on Fedora 22.

thanks

Brad

**Comment by mbland** [comment] 2015-10-06 17:05
Dupe of #754. But guess we'll finally go ahead and update the Gemfile.

**Closed by mbland** 2015-10-06 17:05 UTC
Labels: duplicate
