### ISSUE TITLE
[SideNav] focus state not appearing for mouse navigation in Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#531] opened 2015-09-15 18:45 UTC
*Steps to recreate*
1. When using a mouse (not keyboard tabbing), click on links in sidenav
2. On click, focus state does not appear

http://screencast-o-matic.com/watch/coQoFCfdU0

*Expected behavior*
Upon click, focus state should appear

*Tested on*
OS 10.8
Safari 6.2

**Comment by jpyuda** [comment] 2015-09-15 20:24
Are these links expected to have an "active" state? If not, focus doesn't move with a mouse click.

**Comment by carodew** [comment] 2015-09-15 20:27
Or, rather, it doesn't in Safari.

**Comment by carodew** [comment] 2016-03-17 17:48
Closing since this is expected behavior in Safari.

**Closed by carodew** 2016-03-17 17:48 UTC
Labels: enhancement, visual design
