### ISSUE TITLE
[Name + Address Form] form title vertically too close to input label in Safari

### ISSUE THREAD

**Issue by mollieru** [18F/web-design-standards#590] opened 2015-09-16 17:53 UTC
*Steps to replicate*
Navigat to 'Name' and 'Mailing Address' forms. 
Note the example block titles have padding inconsistent with that of  the 'Sign-in Form'...

![screen shot 2015-09-16 at 1 46 41 pm](https://cloud.githubusercontent.com/assets/3680494/9913253/e719a15a-5c79-11e5-8e14-f82471d61469.png)
vs.
![screen shot 2015-09-16 at 1 46 35 pm](https://cloud.githubusercontent.com/assets/3680494/9913257/efea6f26-5c79-11e5-9ba4-ffdbe3524430.png)
![screen shot 2015-09-16 at 1 46 29 pm](https://cloud.githubusercontent.com/assets/3680494/9913258/efed821a-5c79-11e5-8539-af793c8a5434.png)

*Expected behavior*
Screenshots from Chrome:
![screen shot 2015-09-16 at 1 52 52 pm](https://cloud.githubusercontent.com/assets/3680494/9913314/3f75de0e-5c7a-11e5-8657-5c24bd4f24c5.png)
![screen shot 2015-09-16 at 1 52 47 pm](https://cloud.githubusercontent.com/assets/3680494/9913313/3f74f1a6-5c7a-11e5-9151-b828d2f23914.png)

*Tested on*
OS 10.8
Safari 6.2

**Comment by maya** [comment] 2016-06-10 20:54
Not able to reproduce the issue. Screenshots of the forms in Safari below:

<img width="602" alt="screen shot 2016-06-10 at 1 52 48 pm" src="https://cloud.githubusercontent.com/assets/5249443/15978422/b82a367c-2f12-11e6-978b-4f97f59f89a2.png">

<img width="529" alt="screen shot 2016-06-10 at 1 52 44 pm" src="https://cloud.githubusercontent.com/assets/5249443/15978421/b829c480-2f12-11e6-9f79-430c3faa9ff4.png">

Closing.

**Closed by maya** 2016-06-10 20:54 UTC
Labels: [Category] Front end, [Category] Visual Design, [Priority] Major, [Status] Accepted, [Status] Help wanted, [Type] Bug
