### ISSUE TITLE
[Footer] Focus on social media icons do not align properly.

### ISSUE THREAD

**Issue by angel** [18F/web-design-standards#573] opened 2015-09-16 02:25 UTC
On Chrome, when I tab through the focus does not go around the icon but slightly below it. 
![image](https://cloud.githubusercontent.com/assets/103496/9895018/5e5151f0-5bdf-11e5-826f-bd8239ad6ab4.png)

**Comment by carodew** [comment] 2015-09-16 14:36
related to #347

**Comment by juliaelman** [comment] 2016-05-20 16:04
Closing, as it's a duplicate of #347

**Closed by juliaelman** 2016-05-20 16:04 UTC
Labels: [Status] Backlog, [Type] Bug
