### ISSUE TITLE
Re-open Menu Button  Accordion DropDown not working  Chrome Firefox Windows 7 Windows 8

### ISSUE THREAD

**Issue by njohnson** [18F/web-design-standards#1999] opened 2017-06-29 13:18 UTC
## Description
A few months ago I put in a ticket that the menu button didn't work in Windows 7 and Windows 8 (note at work I do not have access to Windows 8 or Windows 10).   The first time I put this in,  Windows 8 on my home computer outside the work environment and got the same result. 

In your latest version, the accordion dropdown no longer work. The accordions menus did work on the earlier version that I have downloaded and utilizing.  

## Steps to reproduce the issue

1. Step one  -- Go to  https://standards.usa.gov/page-templates/landing/   Windows 7 using Firefox or Chrome.
2. Step two -- desktop  click on a dropdown menu
3. Step three --  responsive  click on menu

## Additional information [optional]

* Relevant research and support documents
* Screen shot images
* Notes
* And so on

**Comment by toolness** [comment] 2017-06-30 13:49
Thanks for the report!

Between steps two and three, do you mean that we should be making our browser window smaller so that it switches from "desktop mode" into "mobile mode"?

I'm trying to reproduce this on Windows 10 and am unable to, but I can try finding a 7/8 machine if needed. Just want to make sure I am doing exactly what you did to reproduce the bug first.

**Comment by toolness** [comment] 2017-06-30 13:52
Also, in step 2, by "a dropdown menu" I assume you mean e.g. the "Section title" dropdown in the nav area?

> ![one](https://user-images.githubusercontent.com/124687/27738608-cf5c22e2-5d79-11e7-86ee-1e9f89bee45a.png)

And in step 3, by "menu" I assume you mean the button at the top-right that shows up when you make the browser window smaller?

> ![two](https://user-images.githubusercontent.com/124687/27738621-dbbee83a-5d79-11e7-8738-327e6c882b95.png)

**Comment by njohnson** [comment] 2017-06-30 15:08
Thank You.  Yes these are the two issues and the images are correct.

  In the previous version of the usds.js.  The only issue was the menu
button on responsive, but the  accordion global menu worked.

In the latest version Neither the menu button nor the global menu works.

I downloaded your latest version and compared with the earlier version that
I am using and looks like there were a great deal of changes around the
accordion and firing of the aria-expanded.

Window 7 is within my company portal and windows 8 is my personal and not
within the company portal.

I dont have access to windows 10

Nancy

**Comment by toolness** [comment] 2017-07-07 12:08
Hi @njohnson, I think I *might* have fixed this bug. Can you try this alternative version of the site and let me know if the bug is still present on it?

http://atul-uswds-test.s3-website-us-east-1.amazonaws.com/

(Note that this URL might go down sometime in the next few days because it's in a temporary location that gets cleared once per week, but if that happens I'll put it back up monday morning.)

**Comment by njohnson** [comment] 2017-07-07 15:07
I just tested chrome snd firefox window 7 and both the menu button and
accordion navigation work fine

Thanks

**Comment by toolness** [comment] 2017-07-07 16:16
Awesome, thanks @njohnson!

(I'm going to classify this as a duplicate of #1993 and close it, since the fix for that issue resolves this one too.)

**Closed by toolness** 2017-07-07 16:16 UTC
