### ISSUE TITLE
[Password reset] validation checkmarks in the "Passwords must" box are not appearing

### ISSUE THREAD

**Issue by carodew** [18F/web-design-standards#458] opened 2015-09-09 14:16 UTC
**Steps to recreate**

1. Open the site in IE11 and navigate to the password reset form. 
2. Type into the first password box and make sure to include one capital letter, one number, and at least 8 characters. 
3. Note that no checkmarks appear next to the password requirements in the blue box. 

**Expected behavior**
Blue checkmarks should appear next to the relevant requirements as they are fulfilled, but they aren't appearing. Might simply be something that won't work in this browser (and that would be ok) but wanted to log it here for discussion. 

**Tested in**
IE 11
Windows 10
SauceLabs

**Comment by colinpmacarthur** [comment] 2015-09-09 19:25
Also happens in IE 8.

**Comment by maya** [comment] 2015-09-09 19:44
@msecret can you look at this since you worked on PW validation. I don't think the issue is the blue checkmarks not appearing, I think it's actually not validating. Bc ie11 is a modern browser and should be able to get background images.

**Comment by carodew** [comment] 2015-09-09 20:18
Just confirmed it's not working in Chrome either.

**Comment by maya** [comment] 2015-09-09 20:20
@msecret yep, for some reason, password validator has stopped working on all browsers. Can you review?

**Comment by msecret** [comment] 2015-09-11 20:50
Fixed with https://github.com/18F/web-design-standards/pull/505

**Closed** 2015-09-14 18:25 UTC
Labels: bug, high
