### ISSUE TITLE
JS Alert / Modal

### ISSUE THREAD

**Issue by dalfaro1** [18F/web-design-standards#1477] opened 2016-09-13 14:40 UTC
JS Alert / Modal
## Title line template: [Website or UI component]: [Brief description]

Is there going to be an Alert / Modal component under development?
For form validation, confirmation, etc,  which is similar to javascript alert?

**Comment by maya** [comment] 2016-09-21 21:31
Hi @dalfaro1, thanks for reaching out about an alert/modal component.

We have alerts here: https://standards.usa.gov/alerts/

We don't have plans to implement a modal at this point in time, however feel free to follow along our roadmap https://standards.usa.gov/about-our-work/product-roadmap/ and project wiki to stay up to date on what we're working on next: https://github.com/18F/web-design-standards/wiki

**Comment by teebolt** [comment] 2017-02-28 16:43
@maya are there concerns around ux or a11y regarding modals? 

also, im getting a 404 on this page - https://standards.usa.gov/about-our-work/product-roadmap/

**Comment by maya** [comment] 2017-02-28 18:40
@teebolt a bit of time has passed since posting that link and the team just restructured the pages, so it looks like the roadmap is now here: https://standards.usa.gov/whats-new/product-roadmap/

For modal usability, I recommend this reading through this article: https://www.nngroup.com/articles/overuse-of-overlays/

Regarding a11y:
- ensure you focus on the the modal content when the button is pressed
- ensure focus doesn't escape the modal window and leak onto the page behind it
- make sure there's an escape button that's also keyboard accessible

**Comment by maya** [comment] 2017-12-06 21:06
Closing as a duplicate of #911.

**Closed by maya** 2017-12-06 21:06 UTC
Labels: [Status] Idea, [Type] Question
