### ISSUE TITLE
[Side navigation] Menu button doesn't work after opening a 2nd level nav item on iPad 2, iOS 8.4

### ISSUE THREAD

**Issue by colinpmacarthur** [18F/web-design-standards#375] opened 2015-08-27 04:06 UTC
Steps to replicate:
1. Go to the standards homepage. 
2. Tap the "Menu" icon and then tap the "Visual Style" link.
3. Tap the "Menu" icon again and then tap the "Colors" link.
4. Now try to tap the "Menu" icon again. Nothing happens.

Video: https://drive.google.com/a/gsa.gov/file/d/0BzVTh-jwYUTHQVNIbGw3eldjY0k/view

**Comment by carodew** [comment] 2015-08-27 21:27
Can anyone replicate this on another iPad?

**Comment by jpyuda** [comment] 2015-08-31 15:05
I can replicate on iPad Air 2 (also running iOS 8.4). Looks like what happens is when clicking a jump link, the page scrolls down a little but no javascript event fires to close the menu. And there's no on-screen control to close it, either. I can confirm that clicking on another one of the top-level links (like Layout System) closes the menu.

This only happens in portrait mode (the sidenav is persistent in landscape)

**Comment by jpyuda** [comment] 2015-08-31 20:18
We may have actually seen different behavior. When following the steps above, the menu opened and would not close for me.

**Comment by carodew** [comment] 2015-08-31 20:18
@colinpmacarthur to find out if it's the same behavior or different or related.

**Comment by colinpmacarthur** [comment] 2015-09-03 16:19
@jpyuda: sounds like we're describing two different bugs? (I can't replicate your experience on my iPad.) @mollieru and @angel -- could you repeat the steps above on your iPads and see whether you have experiences like mine or Yuda's?

**Comment by maya** [comment] 2015-09-09 18:24
@colinpmacarthur I tested this in emulator for the iPad and don't see the issue. Can you confirm if this is still an issue?

![](http://g.recordit.co/P5KHIdapfU.gif)

**Comment by colinpmacarthur** [comment] 2015-09-09 19:16
@maya: Yes, this still persists on the actual device. I've never been able to reproduce it in the emulator.

Do you or @msecret have an actual iPad to try it out on? @angel or @mollieru: could you help us out?

**Comment by maya** [comment] 2015-09-09 19:41
@colinpmacarthur unfortunately we do not have an iPad to test this. This also is feeling like a library-specific bug that I would vote to move to low/post-MVP.

**Comment by carodew** [comment] 2015-09-11 20:27
Colin to investigate further to see if this is just his device.

**Comment by colinpmacarthur** [comment] 2015-09-14 19:40
I can't replicate this issue on my device anymore. @jpyuda -- can you still replicate the issue you described?

**Comment by jpyuda** [comment] 2015-09-14 20:08
It still behaves as I describe but I believe that is as designed. Happy to close this.

**Comment by carodew** [comment] 2015-09-14 20:09
No longer can be replicated.

**Closed by carodew** 2015-09-14 20:09 UTC
Labels: blocked, bug, more information needed, To be triaged
