### ISSUE TITLE
Search box is above top nav in IE11

### ISSUE THREAD

**Issue by bruffridge** [18F/web-design-standards#2023] opened 2017-07-11 20:08 UTC
In IE 11, search box is above top navigation in usa-header-basic instead of on same level. [view bug](https://standards.usa.gov/components/headers/basic-mega/)

<img width="962" alt="screen shot 2017-07-11 at 12 04 26 pm" src="https://user-images.githubusercontent.com/1322063/28088224-7bc43082-6631-11e7-9623-8c9f389f5732.png">

**Comment by toolness** [comment] 2017-07-12 10:57
Thanks @bruffridge! I think this is a duplicate of #1984, right?  You participated in that issue, too, so I don't want to mark this as a duplicate without your acknowledgement...

**Comment by toolness** [comment] 2017-07-12 14:55
Oh geez, I was really out of it this morning! Never mind, this *is* totally different from #1984, my bad.

**Closed** 2017-07-12 14:59 UTC
