### ISSUE TITLE
contributing.md: Clarify dependencies for local development

### ISSUE THREAD

**Issue by antislice** [18F/web-design-standards#1287] opened 2016-06-20 22:40 UTC
## Issue type

Documentation ([Build project locally](https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md#building-the-project-locally-with-gulp))
## Description

I was helping a teammate set up this project (on OS X) to use as a template for a different set of design standards, and her computer wasn't set up for any sort of development (primarily a designer). The `uswds` NPM package relies on the Bundler gem & command line tools, which aren't listed as dependencies. Most developers (on OS X) will have the command line tools installed, and many will have Bundler installed, but it's still worth a mention to save frustration.

Suggestion: add a sentence listing Bundler and OS X command line tools as dependencies with a link to how to install.
## Steps to reproduce the issue
1. Have computer with zero dev environment set up.
2. Follow [Build project locally](https://github.com/18F/web-design-standards/blob/staging/CONTRIBUTING.md#building-the-project-locally-with-gulp) instructions
3. Run into error when `uswds` package tries to run `bundle` (Bundler gem not installed) and again when installing `ffi` gem (command-line tools not installed)

**Comment by joshbruce** [comment] 2016-06-20 23:45
Would something like this have helped?

--------------

#### Confirm Ruby

To serve the site locally, we will need Ruby. Confirm Ruby is installed:

`$ gem -v`

If you do not see a version number, [install RubyGems](https://rubygems.org/pages/download).

#### Confirm Ruby Bundler

`$ bundle -v`

If you do not see a version number, and you have confirmed Ruby:

`$ gem install bundler`

#### Confirm NPM

To install the required modules, we will need Node Package Manager (NPM). Confirm NPM is available:

`$ npm -v`

If you do not see a version number, [install Node.js](https://nodejs.org/en/download/).

#### Confirm Gulp 

To compile the site, we will need Gulp - an NPM module. Confirm Gulp is available:

`$ gulp -v`

If you do not see a version number, and you have confirmed NPM:

`$ npm install --global gulp-cli`

#### Serve the site locally

If you've made it here, you are ready to go. Launch Terminal (OS X) or Command Prompt (Windows) and move to the locally cloned repository.

`$ cd ~/path/to/cloned/repo/sam-web-design-standards`

**Update gems (this could take a moment):**

First time: `$ bundle install`

To update to latest versions: `$ bundle update`

Note: Sometimes you may get an error asking you to update a module. If you run `$ bundle update`, and see Gemfile.lock in your commit, discard changes before submitting a pull request.

**Update node modules (this could take a moment, especially the first time):**

Firt time: `$npm install`

To update: `$ npm update`

**Serve the site:**

`$ gulp website:serve`

- or -

`$ npm start`

After running this command, you should be able to view
the Standards website locally (http://127.0.0.1:4000).

This also sets up gulp and Jekyll to watch for file changes; so, as you update files, you should only need to refresh your browser.

**Comment by antislice** [comment] 2016-06-22 23:05
That's more detailed than I had in mind, but I would know what to check for for ruby & the command-line tools. And I was raising the issue to help out less experienced people. Otherwise looks good.

Installing the `uswds` npm package runs a bundle install during `npm install`, but it doesn't hurt to list it separately.

**Comment by joshbruce** [comment] 2016-06-23 12:26
That's fair. Do you think it would be worth separating the environment requirements from the actual serving?

Because the `npm` commands still use the `gulp` commands, the "confirm" pieces are only there to setup the environment itself. Beyond that, a user can use `npm` or `gulp` commands to do everything else.

**Comment by antislice** [comment] 2016-06-24 18:45
Yeah, I think it'd be worth it. If you're new to this kind of thing, the confirmation steps will be valuable to you, and if you're experienced you'll be more interested in getting going.

**Comment by juliaelman** [comment] 2016-11-03 15:50
@antislice thank you for submitting this issue! We separated out the website into it's own repo and updated our documentation to outline what needs to be installed on you system in order to get the site to run locally.

In terms of adding a reference Mac OS command line tools, we are trying to be as OS agnostic as possible when it comes to our documentation. However, we are always happy to answer any/all questions you may have.

**Comment by juliaelman** [comment] 2016-11-03 17:43
The PR has now been merged. See new docs updated here: https://github.com/18F/web-design-standards-docs#running-locally

Hope this is more helpful for getting the website up and running on their local machines! ❤️  🇺🇸

**Closed by juliaelman** 2016-11-03 17:43 UTC
Labels: Q1 2017, [Category] Documentation, [Type] Enhancement
