### ISSUE TITLE
Using "Standards" in our name establishes misleading expectations

### ISSUE THREAD

**Issue by thisisdano** [18F/web-design-standards#2240] opened 2017-11-16 18:59 UTC
Since the beginning of the USWDS, we've been aware of the disconnect between the meaning of "standards" in a government context and what the [USWD]Standards actually are: voluntary guidance around best practices and a practical toolkit to build from that guidance. Plainly, we know that the Standards aren't _standards_ and that's a problem. Since we're more interested in a living system of voluntary guidelines than a fixed mandatory standard, it makes sense to think seriously about changing our name — and we are thinking about this now as part of [a larger process of refining our mission, principles, and product](https://github.com/18F/web-design-standards/wiki/Recap%3A-Ideation-session-1) as the Standards matures.

Words have meaning, especially in government. It's a big thing to change a name, just as it's a big thing to misrepresent with that name. So we need to take this seriously.

Variations on this issue have popped up like :mushroom::mushroom::mushroom: for some time:

- Could you make it clearer that this is not some sort of official regulation?
 (https://github.com/18F/web-design-standards-docs/issues/197)
- Mandatory standards? (https://github.com/18F/web-design-standards/issues/1755)
- Clarify the role and status of this project in the homepage text (https://github.com/18F/web-design-standards/issues/846)
- Call it the U.S. Web Design System  (https://github.com/18F/web-design-standards/issues/1518)

At one point we reached out to NIST with our question about naming, and this is how Patricia Harris at NIST replied:

> Thank you for bringing your question regarding your group’s the use of the word “standard” to the NIST Standards Coordination Office. NIST is the chair of the Interagency Committee on Standards Policy (ICSP), so matters such as this are of great interest to us. I have consulted with a number of SCO staff with experience in standards development, implementation, and standards policy in the federal sector to comment and advise. Following is a summary of our viewpoints.
>
> Based on our experience, we can understand why the agency representatives you are working with are confused about the use of the word “standard” in the context of your work.
>
> Within the community of federal agencies, the generally accepted understanding of the term “standard” is set forth in the NTTAA and the recent revision to OMB Circular A119. This law and policy direct federal agencies to rely on standards developed by the private sector using a consensus-based process (some caveats and exceptions are noted). Some of the confusion you are seeing from your agency colleagues may be based on their knowledge of A119 and their expectation that standards are developed in the private sector (primarily).
>
> In those cases, where the federal government develops its own standards, it is generally in the form of a regulation that is required for use by either the regulated community in the private sector or a requirement for federal procurement or use within the federal government (often in the form of an executive order or OMB policy memo.) This general acceptance that standards intended for use within the federal government are most often mandatory is the other source of confusion.
>
> Your group’s decision to use the term ‘standards’ is entirely your decision to make. However, it may not be the best word to use. Referring to your document set as the ‘U.S. Web Design Standards’ could denote to some that this is a U.S. national standard and thereby assume that is applicable beyond the federal government and has the full authority of the U.S. federal government. We suggest your group consider a title that more clearly denotes that 1) this is a US federal government effort and 2) that this is not a mandatory standard. Some ideas to suggest: “Guidelines for federal . . .” or “Best Practices for federal . . . .”
>
> We’d be happy to discuss this further with you and others. Let me know if you think a conference call with your team to discuss this further would be beneficial. Fyi, I have taken the liberty of cc’ing the GSA representatives to the ICSP, Jeffrey Thurston and Jennifer Moffatt.
>
> Thank you for reaching out to NIST and giving us an opportunity to comment and advise.

- - -

I believe the key paragraph is this one:
> Your group’s decision to use the term ‘standards’ is entirely your decision to make. However, it may not be the best word to use. Referring to your document set as the ‘U.S. Web Design Standards’ could denote to some that this is a U.S. national standard and thereby assume that is applicable beyond the federal government and has the full authority of the U.S. federal government. We suggest your group consider a title that more clearly denotes that 1) this is a US federal government effort and 2) that this is not a mandatory standard. Some ideas to suggest: “Guidelines for federal . . .” or “Best Practices for federal . . . .”

This is guidance we implemented at the copy level, and I think we've been responsible in communicating that this system is not mandatory. But it is possible that this is not enough, and the distraction of this continued naming issue, in addition to the very real confusion it causes, is reason enough to be serious about considering a name change.

The USWDS is commonly called "the Standards" and this name has stuck. For better and for worse, this name has recognition and connotes a certain gravitas. The mission of the USWDS has importance and gravitas we wish to maintain, even as we push for living, iterative, opt-in guidance. What kind of a change can we make that makes sense, provides continuity with the current name, and furthers our mission. This is not a simple question.

We expect that this will be a place for folks beyond the Core team to discuss this issue, and it is the appropriate place to discuss this issue. Anyone is welcome to join in. Welcome!

**Comment by wslack** [comment] 2017-11-16 21:17
I would suggest people read through https://github.com/18F/web-design-standards/issues/1518 for the thoughtful comments - thanks for referencing that issue Dan. I listed some alternative name ideas there.

I don't think the current name misrepresents, though it does have a potential of confusion. We're in a space that intersects several competing sets of norms, and in the world of web design, a "design standard" isn't legally required. It represents best practice and allows for a consistent experience (e.g. http://www.justinmarxdesign.com/nordstrom-ux-design-standards/ https://www.uxmatters.com/mt/archives/2014/08/principles-over-standards.php https://uxplanet.org/7-deadly-ux-sins-and-how-to-avoid-them-f47292e1f5dd http://digitaldesignstandards.com/ http://design.comcast.com/standards/)

A "design standard" is policy, not a legal mandate.

Here is the policy guidance from [OMB M-17-06](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/memoranda/2017/m-17-06.pdf):

> 18. Ensure a Consistent Look and Feel Across Websites
> Common user interface components and visual styles help create a seamless transition across an
> agency’s websites and improve the ease with which the public can find information.
> Federal Agencies should ensure a consistent look and feel of their public facing websites and digital services.
> 
> The U.S. Website Design Standards, found at https://playbook.cio.gov/designstandards/gettingstarted/,
> is available to all agencies to assist with this process. 

We know from talking with partners that the "standards" name has been helpful within agency internal discussions about web design - they have been useful resources "in the corner" of developers arguing for better practices on their websites. This is in line with the policy from OMB.

I don't think its quite fair to say, within that context, that the USWDS are supposed to simply be "voluntary guidelines." They are intended to assist agencies in **doing the right thing** and having standards - though agencies can promulgate their own to serve the OMB ask, instead of leaning on our general product. US government web design is in a better state right now because people could "lean on" the standards to do the right thing for the users.

And in line with the NIST guidance, the USWDS are meant to "import" best private industry practice into the government. They are completely in line with that part of the guidance.

My suggestion would be to determine what you want the name to accomplish and then look at various possibilities against that criteria of success. I agree that "standards" can cause confusion, but if possible, I don't want to give up all of the benefits that the current name allows for the government .

**Comment by AndreaSigz** [comment] 2017-11-16 21:21
I will also share this thread @thisisdano to the listserv, replying to the several emails about this in the last few days; directing them to this GitHub issue

**Comment by thisisdano** [comment] 2017-11-16 21:36
@AndreaSigz I'm sending it out to the listserv now :)

**Comment by thisisdano** [comment] 2017-11-16 21:49
@wslack Thank you for jumping in! I definitely realize this is an issue with roots and existing thoughts. The `Standards` vs `Design Standards` distinction really resonates with me because of how familiar I am with design standards, standards manuals, etc. It's definitely aligned with the [Design Standards Manuals](https://babel.hathitrust.org/cgi/pt?id=uiug.30112106662312;view=1up;seq=5) developed for the Federal Design Improvement Program in the 1970s. (Which I truly 😍 btw.)

And I think you're right, _misleading_ is probably a little harsh. But I also think it's real, and the distinction between a standard (as in OMB Circular A119) and a design standard (perhaps more of a term of art) is not as clear in the government context.

> My suggestion would be to determine what you want the name to accomplish and then look at various possibilities against that criteria of success. I agree that "standards" can cause confusion, but if possible, I don't want to give up all of the benefits that the current name allows for the government. I wonder what other names can continue these benefits and be accurate in industry parlance without the possible confusion that's present today.

☝️ This is good advice.

**Comment by konklone** [comment] 2017-11-16 22:07
> I agree that "standards" can cause confusion, but if possible, I don't want to give up all of the benefits that the current name allows for the government.

I think the issue is that, to the extent there are benefits that the current name allows for the government, it's based on the "gravitas" the word "standards" has in the government, which is **directly connected** to the general government expectation that standards are mandatory.

So I think it's difficult to have our cake and eat it too on this one, and would recommend we move to `U.S. Web Design Resources` or `U.S. Web Design Toolkit`, which may have less gravitas, but is more likely to communicate the role of the project more effectively and generate less confusion.

**Comment by thisisdano** [comment] 2017-11-16 22:13
> I think the issue is that, to the extent there are benefits that the current name allows for the government, it's based on the "gravitas" the word "standards" has in the government, which is directly connected to the general government expectation that standards are mandatory.

Oh boy that. It's unfortunately kinda "part of this complete breakfast"-y. But undeniably effective.

**Comment by danamuses** [comment] 2017-11-16 22:48
From the perspective of an agency that has begun to implement the USWDS across our platforms, I have found it to be incredible helpful in my outreach to stakeholders that these are "design standards." I like to point out that there is flexibility within the standards (e.g., multiple ways to apply the font choices, a pretty wide color palette). I also often frequently note that these standards have been developed based on expertise in usability and accessibility--so the fonts were chosen because they are readable (and not "just because" or "they look nice"), etc.  If this were simply a "toolkit" or "resources" I would have a much harder time selling them as something we should adopt and implement. So put me as a check mark in the "keep name" column, please!

**Comment by thecapacity** [comment] 2017-11-16 22:52
I for one am not sure I understand the nuance, but I would leave the name because I think the cognitive work isn't worth the collective value. 

Also my read of [A119](https://www.whitehouse.gov/omb/circulars_a119) perhaps differs from NIST, which may not be surprising given some of my other views on `FIPS` and `SP-*` however it seems to:
  1. Define standards as *voluntary* which is entirely what the USWDS are... i.e. they seem aligned w/ the definition and 
  2. It seems to empower NIST to _"coordinate conformity assessment activities of the agencies..."_ vs. relying on NIST to *define* them, i.e. I read that as NIST is fully empowered (but not obligated) to build an assessment tool, much as they've done for other "standards" (like IPv6)

While I'm on the subject of IPv6, I'd note that NIST didn't define that standard (though I'm sure they had a valuable part in it) and it's entirely voluntary as a technology standard - i.e. if you don't want to be part of that community you don't use it... and having a standard mandated comes more directly (e.g. as part of an OMB action)

**Comment by lanebecker** [comment] 2017-11-16 23:47
Curious about whether or not the phrase "design system" was rejected, and if so for what reason. -- [Earlier discussion](https://github.com/18F/web-design-standards/issues/1518) doesn't appear to end conclusively one way or the other, and it does seem to be the thing the [CMS fork/Nava team](https://design.cms.gov/) went with.

**Comment by andrewmaier** [comment] 2017-11-16 23:50
Two points:

1. It is at the very least _misleading_ to collectively name a set of visual styles and design patterns as "a" standard. 

2. [Context matters more than consistency](https://gettingreal.37signals.com/ch09_Context_Over_Consistency.php) in design. My vote would be to offer guidelines in the spirit of, say, Apple's Human Interface Guidelines. Design guidelines encourage consistency while _also_ empowering folks to make well informed decisions about the tradeoffs they're making throughout the design process.

**Comment by thisisdano** [comment] 2017-11-17 00:08
@lanebecker I believe "design system" is probably the most accurate descriptor of what the USWDS is — at least in contemporary usage. I'm not sure what currency that usage has outside design professionals (yet) but it is the way I describe the USWDS to others, and I would say that's how we think of it internally as well. The Nava/CMS system is very interesting to us, and a useful example in many ways!

@andrewmaier I'm sympathetic to that point of view, and I'm curious how more high-level guidance (at something of the level of HIG) might be important to our system, because, as you've probably seen yourself, USWDS projects deviate from the standard styles far more than they conform to them. I think this is a feature, not a bug, and we expect that this will continue. And because it will, higher-level guidelines are much more important, since we wouldn't want necessary customization to be inconsistent with critical best practices. How can we encourage adaptability within a greater system of good-for-people design (_as a verb_) consistency?

**Comment by philipashlock** [comment] 2017-11-17 00:29
One of the main reasons why this is such a hot button issue is that the existing use and understanding of the term "standards" in government is quite confusing and ambiguous to begin with. So this isn't just a matter of sowing new confusion, it's adding confusion on top of existing confusion. That is of course further exacerbated by simply referring to this work as "The Standards." 

While the folks who focus on web content and web design may be less familiar with these issues, it seems to add unnecessary confusion to something that would already benefit from more clarity. Personally, I think the more appropriate term which is already well established for this community of practice is the U.S. Web Design Styleguide (maintaining the USWDS abbreviation). To the extent that the styleguide incorporates things that are explicitly mandated (like Section 508 accessibility requirements) perhaps that can provide extra weight of the argument for those who need it. Given how passive the language around the reference to USWDS is in M-17-06, I think it's quite a stretch to treat it as a standard in the form the term more commonly takes in government and I don't think that was OMB's intent. 

---

Here's my broader diatribe on the term "standards" in the U.S. Government...

Ambiguity and miscommunication around the word "standards" is not unique to government and many efforts outside of government avoid using the term or only use it with more articulate qualifiers. For example, the W3C which is the main standards body for the specifications that make the web work, refers to their work product as "recommendations" rather than "standards." In part, I think this is to connote that you can rarely designate a standard by fiat, something only truly becomes recognized as a standard through broad real-world adoption. This is where the government is unique, it can and does designate things by fiat. In fact many laws and regulations are effectively synonymous with the use of the word "standard" in government. When someone says, "is that thing built to code?" they're asking if it's built to the standards defined by government in law. 

As government becomes increasingly digital and data driven, the ambiguity around this term in Federal policy seems to be more problematic. While many folks, including myself, have often pointed to the [NTAA](https://www.nist.gov/standardsgov/national-technology-transfer-and-advancement-act-1995) and it's authority thru [OMB A-119](https://obamawhitehouse.archives.gov/sites/default/files/omb/inforeg/revised_circular_a-119_as_of_1_22.pdf) as the main policy governing standards and participation in standards development with regard to data and digital systems, I don't think the law was really written with this use in mind. Or to the extent that it was, it seems to be more of an afterthought. In practice it doesn't seem to be serving this purpose very well as you can see by the lack of any mention of data standards or digital interoperability in the annual reporting for A-119. 

My understanding of A-119 is that it was primarily meant to focus on standards that govern the build and process around physical things to ensure they meet minimum requirements for how they're produced or perform in terms of quality, safety, reliability, environment, etc. You can consult the current copy of [A-119](https://obamawhitehouse.archives.gov/sites/default/files/omb/inforeg/revised_circular_a-119_as_of_1_22.pdf) for the full definition (the [copy](https://www.whitehouse.gov/omb/circulars_a119) on Whitehouse.gov seems out of date) and it does include a wide range of descriptors to define a standard. Many of these seem to be framed more around "physical things" like I mentioned earlier and there's similar language used to describe [NIST's purpose](https://www.law.cornell.edu/uscode/text/15/271) e.g. "manufacturing technology, quality control, and techniques for ensuring product reliability" and "Precise measurements, calibrations, and standards help United States industry and manufacturing concerns compete strongly in world markets." 

While the original definition in the NTTA is quite short (_"the term `technical standards' means performance-based or design-specific technical specifications and related management systems practices"_) the incarnation in A-119's definition as well NIST's charter seem to includes some language that's more explicitly applicable to data and digital systems, but they're still short and brief compared to all the focus on these other things. In A-119 it's _"formats for information and communication exchange"_ and in [15 U.S. Code § 272](https://www.law.cornell.edu/uscode/text/15/272) it's "_develop and test standard interfaces, communication protocols, and data structures for computer and related telecommunications systems;_" In practice the main activities I seem to be aware of that fall into this category are things that also have more specific mandates under this like NIST's role in ensuring minimum standards for cybersecurity or digital infrastructure and data standards for voting systems whereas broader work for data standards often tends to come out of non-NIST efforts, e.g. NIEM, or through specific mandates, e.g. the DATA Act., M-13-13 and data.json, M-16-21 and code.json, etc. It turns out that [OMB A-130](https://www.whitehouse.gov/sites/whitehouse.gov/files/omb/circulars/A130/a130revised.pdf) does give the Department of Commerce (NIST's parent) more emphasis on having government-wide responsibilities here and GSA is also named as being a partner. A-130 also puts emphasis on "open data standards" but I'm not aware of much guidance or definition to support those roles and terms. For interoperability between digital systems most developed countries have something like a "National Interoperability Framework" but I'm not aware of equivalent guidance in the U.S. Government. 

As has been already mentioned in comments here, it seems like it would be better to define the use of a standard in terms of what goal(s) standardization achieves rather than simply use the types of specifications or processes that define the context where standardization is applicable or achieved. In the case of A-119 it seems like the main purpose is "conformity assessment" - to be able to have an apples-to-apples comparison to ensure something meets a minimum set of requirements. This is different from the purpose of most standards in a digital context, or at least it's a much more limited scope of purpose. Here's how it's defined in A-119 

>What is Conformity Assessment?
>
>"Conformity assessment" is a demonstration, whether directly or indirectly, that specified requirements relating to a product, process, system, person, or body are fulfilled. Conformity assessment includes sampling and testing, inspection, supplier’s declaration of conformity, certification, and management system assessment and registration. Conformity assessment also includes accreditation of the competence of those activities.

We should put more thought into the use of standardization or "conformity" for multiple purposes beyond that. I started to list some example below, but some of these will surely overlap or serve as foundations for the other. 

* Conformity to ensure mutual understanding (definition of words, fundamental units of measure)
* Conformity to ensure comparability - enabling conformity assessment to ensure something meets a minimum requirement or best practice (e.g. standards for safety or environmental regulations)
* Conformity to ensure accessibility
* Conformity to ensure aggregate harmonization
* Conformity to ensure functional interoperability 

On a related note, I've been looking for an anatomy of digital and data standards that break it down into the multiple layers of standardization. I started to sketch that out in [this comment](https://github.com/18F/data-act-pilot/issues/161#issuecomment-139415248).

**Comment by joshbruce** [comment] 2017-11-17 03:17
Agreed. Very legalize in this space. Law, policy, standard, and guideline all carry different weight. I actually appreciated that when I saw more use of the word "system" as the final "s". As that's really what we're talking about anyway.

If you don't use the HTML patterns, the styles, _and_ JS in combination it doesn't work the same...at least not compared to the examples. It *does* work, that's kinda the point of using a progressive enhancement, yeah?

So, yeah, my two cents (skimming through, just toggle the standards for a system, you're good. Probably the whole point of this and the other conversations mentioned. :)

System: a set of things working together as parts of a mechanism or an interconnecting network. _Computing_ a group of related hardware units or programs or both, especially when dedicated to a single application.

**Comment by bruce-usab** [comment] 2017-11-17 13:17
You have picked a name for the product that interfers with it adoption.  OTOH, the terrible name has generated buzz, and buzz is good -- but I have hard time believing that this one naive choice has been a net possitive.  What if all this churn over the terible name had put into implementation of a terrific product?

I am rifting off @wslack post here.  Where is the reply button?

> I think this says that it is policy for agencies to have a consistent look and feel - which means that agencies should be working off of "design standards." The USWDS are an example set of standards.

I think the correct term is “reference design.”  The USWDS is a reference design.

> Finally, in line with the NIST guidance, the USWDS are meant to "import" best private industry practice into the government. They are completely in line with that part of the guidance.

I respectfully disagree.  Here is what ANSI says standards development looks like:
Consensus must be reached by representatives from materially affected and interested parties
Standards are required to undergo public reviews when any member of the public may submit comments
Comments from the consensus body and public review commenters must be responded to in good faith
An appeals process is required

Yes, lots of that overlaps with an Open Source mindset and using a public forum like github.  But as the saying goes, close only counts with horseshoes and handgrenades.

The name is a problem.  Please fix the problem rather than trying to argue it away.

> My suggestion would be to determine what you want the name to accomplish and then look at various possibilities against that criteria of success.

+1

> I agree that "standards" can cause confusion, but if possible, I don't want to give up all of the benefits that the current name allows for the government.

I agree with what @konklone wrote:
> I think the issue is that, to the extent there are benefits that the current name allows for the government, it's based on the "gravitas" the word "standards" has in the government, which is directly connected to the general government expectation that standards are mandatory.

> I wonder what other names can continue these benefits and be accurate in industry parlance without the possible confusion that's present today.

Reference Design.  Template.  Model.  Paragon.

**Comment by jpyuda** [comment] 2017-11-17 13:19
Definitely change to design system. It's really really not worth the cognitive (and actual!) workload to continue using the "standards" name.

**Comment by MarkUCDC** [comment] 2017-11-17 13:56
I'm going to feel quite small with my trite and short comments after the thoughtful, reasoned discourse above, but here goes:

Focus on the _mission_ of the "Standards":  to provide an working example, not force the solution.  To that extent, It's a MODEL.  SO, **US Government Web Design Model** would be my suggestion.  

The clear indication is that "Standards" in a government context is the wrong verbiage, so if my name doesn't meet your fancy, I suggest the team identify a proposed name, and ask the group to comment on it.  Just pick a name that doesn't imply a mandate: "example", "prototype", "Best Practice", "Reference Option", "Template", "Resource", "Library" are some options. 

Ultimately, the conversation is a distraction. This seems a simple thing, and I'm a bit confused by the fact that this hasn't been addressed earlier.

**Comment by wslack** [comment] 2017-11-17 15:45
Lots of good comments in this thread.

@bruce-usab: Thank you for the critique! All of those names can work for me, and I accept that the USWDS didn't conform to those bullets from NIST - I was saying more generally that the idea of the standards is in line with that use of the term.

I think "reference design" does the best job of any name I've seen so far of keeping the benefits of the current name. I'm personally doubtful that "design system" is clear, but user research is a better judge of that than I.

**Comment by gillick** [comment] 2017-11-17 17:42
I found out yesterday that one of the firms my agency employs has been working with the guidelines (I will never use the word standards for this reference) for another agency site, not because it "likes" them, but because it was under the impression that they were official US government standards.  Perhaps the name confused them.

I shared the news with that agency today, that a re-naming might be in the offing. To quote: "Glad to see that they are listening."

**Comment by gillick** [comment] 2017-11-17 18:14
I should mention that context matters. There are enough quotes from 18F folks scattered across podcasts and blogs, adding bits of puffery to the guidelines, that it would be easy to mistake them for "standards." 

- "Design Standards - Follow current government design standards when creating new websites or making significant changes to existing websites." ("Checklist of **Requirements** for Federal Websites and Digital Services", https://www.digitalgov.gov/resources/checklist-of-requirements-for-federal-digital-services/)

- "The U.S. Web Design Standards are the U.S. government’s very own set of common UI components and visual styles for websites." ("Introducing the US Web Design Standards", https://18f.gsa.gov/2015/09/28/web-design-standards/)
 
- "With the new standards comes a slight modification to play three of the U.S. Digital Services Playbook (“Make it simple and intuitive”) from “Create or use an existing, simple, and flexible design style guide for the service” to “Use a simple and flexible design style guide for the service. Use the U.S. Web Design Standards as a default.”" ("USDS publishes design standards for federal government websites", https://govfresh.com/2015/09/usds-publishes-design-standards-for-federal-government-websites/)
 
- "The Federal Government has recently took up the challenge of documenting an official guide for how federal websites should be designed, structured and presented to the public." ("US Federal Government Releases Web Design Standards", http://washingtonguard.org/us-federal-government-releases-web-design-standards/)

The list/confusion goes on...

**Comment by thisisdano** [comment] 2017-11-17 19:18
@gillick It's good point to reiterate that words (and a name is a big word) create an echo that persists, some of which you intend and control, and some of which you do not. Wherever we go with this, hopefully it's with a thoughtful understanding of the intended and unintended echoes and effects. 

And I'm very glad to be listening!

**Comment by brendansudol** [comment] 2017-11-17 19:58
adding a virtual vote for US Web Design **System**; a few reasons / externalities: it better defines what it is, it's a term used throughout the community for this type of thing, it keeps USWDS nickname intact

**Comment by gillick** [comment] 2017-11-17 20:09
Honestly, I don't even think the U.S. belongs in the name. 

I've got 10 bureaus in my agency, some of which are larger than other agencies. If we got together with Defense (another agency with some hefty sub-parts) or State and published web guidance to share with the rest of the government, we still probably wouldn't put US in the name -- and we'd probably have more claim to it.

The US implies an elevation of the system, above what it has earned or been granted.

**Comment by thisisdano** [comment] 2017-11-17 22:44
**A note to all following this issue:** Hi! It's good to hear so any voices from so many different corners of government. It is quite thrilling to be in good company.

I think this thread has been great and but I also want to set realistic expectations around this issue:

1. We will not be making any kind of decision on our name in the immediate future. This issue is a component of our current long-term planning, and we're not going to be making any decisions in 2017 (that may sound dramatic, but there are only a few weeks remaining).
2. I will keep the thread up to date on our progress.
3. We will work in public as much as possible.
4. We will continue to solicit a broad range of opinions, and try hard to hear quiet voices.

Thanks!
🌾

**Comment by philipashlock** [comment] 2017-11-28 23:14
I appreciate you setting expectations and I also think it's reasonable that this might not get sorted out until January or later, but there is some dissonance in emphasizing the discussion out in the open while signaling uncertainty about actually being responsive to that discussion. That same dissonance parallels the association with the main federal standards policy which is largely focused on working with voluntary consensus standards bodies. This means working with outside stakeholder groups in the public including private industry rather than defining standards unilaterally or unnecessarily creating government specific standards. Even if the main folks who author the USWDS think they're satisfying this by incorporating best practices already established outside government, that doesn't seem like a genuine way to incorporate input from the relevant stakeholder groups. 

However, in this regard I think the USWDS use case further helps convey why the current terminology and policy for standards in government is so incomplete and subject to confusion. Much like I tried to break down the different purposes of standards in my earlier [comment](https://github.com/18F/web-design-standards/issues/2240#issuecomment-345107738), I would argue that there are primarily three distinct types of standardization that the USWDS are meant to support: 1) accessibility 2) usability 3) identity. 

Of these three only one of them, accessibility, really fits under the main definition for standards in the federal government. In the case of accessibility, there is a mandated regulation around it (Section 508) and there are relevant voluntary consensus standards bodies we should both defer to and where we should have an active voice as outlined in A-119 (e.g. the W3C and Web Content Accessibility Guidelines). 

Standardized design conventions and best practices for usability tend to be more informal and organic and rarely have a standards body around them, but clear conventions and best practices are still easy to identify and usually we should adopt them where appropriate. For the web this might include avoiding popups or using hamburger icons for menus. Examples of these types of usability "standards" out in the physical world include things like orange coffeepots to denote decaf coffee or the arrow next to the gas gauge helping you know which side of your rental car the gas tank is on.

The idea of a standardized identity or styleguide is probably the most at odds with the principles of A-119, because by definition it is meant to be specific to the federal government.  However, I think this is one of the main goals of the USWDS. 

I hope this illustrates all the many different kinds of standards we might be talking about when referring to something like the USWDS. While I'm strongly in favor of removing the term "standards" from the name of USWDS, I think the more important principle is that we should always be extra articulate when talking about standards in government and when we hear someone else talking about standards in government, we should never assume they're talking about the same thing we are. This is much like the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle), one of the fundamental concepts that underlies that standards that make the internet work: "be conservative in what you do, be liberal in what you accept from others" 

Since we have so much miscommunication around the word "standard" we should put extra effort into being explicit when we say it and be extra unassuming when we hear others say it.

**Comment by gbinal** [comment] 2017-12-15 19:18
As an aside, I want to applaud this project for its continued success.  It has been re-used by [scores of government websites](https://github.com/18F/web-design-standards/blob/develop/WHO_IS_USING_USWDS.md) and is a great example of open source in government.  No one has to use this project but for those who want to, it's a really solid resource that saves time and money, while normalizing the look and feel of government websites.  The [1,028 closed issues](https://github.com/18F/web-design-standards/issues?q=is%3Aissue+is%3Aclosed) and [1,050 closed pull requests](https://github.com/18F/web-design-standards/pulls?q=is%3Apr+is%3Aclosed) speak to the robust collaboration that continues with this project.  I haven't worked on it but I sure appreciate those who have.  

Personally, I've been amazed at the frustration and annoyance that has been directed at the project's name.  Despite reading all of the threads over the years about it, I still don't understand why those who want to use it, can use it and those who don't want, don't have to, especially given all of the work that we all have in front of us.  

But it seems clear to me that the move is to go on and change the name.  My suggestion:  

* Pick one of the words that starts with `S` that have been suggested above.  
* Do some research to ensure that the candidate for the new word to replace `standards` doesn't trigger some other similar problem.  
* Go ahead and put in the effort to change the materials and the project URL and set up redirects for the old URLs.  
* Move on in life and keep delivering.

**Comment by thisisdano** [comment] 2017-12-15 19:36
@gbinal That nice to hear. I tend to agree with your suggestions and expect that this will be the way we go. Furthermore, the `S` word at the top of the leaderboard is `System` — as this is current accepted name for what the USWDS is outside of government.

[Some other examples of design systems](https://www.invisionapp.com/blog/design-systems/)

**Comment by bendygirl** [comment] 2018-01-16 23:09
Hi, it's been a while, a month to be exact. 

What's the plan on removing "Standards" as this is a clear term in govspeak and not so much for this repository.  I've been hearing the words "Compliance with the web design standards" now from a couple of places. I remind them you can't have compliance with something that is not a regulation or law. So it'd be incredibly helpful to me not to have to continually explain this to folks who know what "standards" and "Compliance" are but not necessarily what design or development are.

**Comment by bendygirl** [comment] 2018-01-16 23:24
Is this now OBE with this issue https://github.com/18F/web-design-standards/issues/2300
specifically this: 

>Change name and shorthand throughout main repo and docs site 
> Write a blog post to explain the change as relevant to the work we’re doing and what we’re providing -- @thisisdano
> Less about the name, more about the benefit, pedagogy — benefits of system design thinking, similar to standardization without the baggage, rigidity
>  Pick a URL: designsystem.gov / designsystem.digital.gov -- @thisisdano cc @jeremyzilar

So, I can't read the accompanying document, but is there a time frame for when the blog post and name change will take place?

**Comment by maya** [comment] 2018-01-16 23:42
@bendygirl thanks for reaching out. Yes, #2300 is where we're tracking work needed to be done for the name change. It's a top priority for the team and we're working on the announcement this sprint and will be able to share it with you soon. Thanks for your patience.

**Comment by bendygirl** [comment] 2018-01-16 23:45
@maya I've also noted this on the content list, and I referenced my comment so anyone who hits the link should be able to follow along. You might want to respond to the email if possible that work is being done in this vein. I have been going through the issue que to see since this open ticket wasn't apparently cross referenced (at least not that I could find).

Thanks

**Comment by maya** [comment] 2018-01-16 23:50
@bendygirl cross-referenced now and we'll share the announcement via the email as well, thanks!

**Comment by bendygirl** [comment] 2018-01-16 23:52
I've posted to the internal drupal lists so the govies also know where to find the info on this moving forward.

**Comment by maya** [comment] 2018-01-17 21:18
Hello everyone,

After listening to a lot of thoughtful feedback and discussion from a wide range of voices in the government web community, **we’ve decided to change our name to the U.S. Web Design System**. (You don’t need to update any code for this, it’s simply an announcement.)

Here’s why we’re making the change: 

- We wanted to clarify our project: they’re not mandatory standards, but a system of tools and guidelines that anyone can choose to build better government websites and services. 
- _Standards_ also suggests something fixed and rigid, which is the opposite of our goal to create a design system that’s flexible, modular, and always learning from its users and modern best practices. 
- It’s a system whose various parts (e.g. visual design, accessible color combinations, interactive components, page templates, etc...) can be used bit by bit, all together, or extended into something new. 
- A **Design System** is the real-world name for what we do and what we are. All kinds of organizations—from governments to large corporations—use design systems to help guide the design and development of their digital products. So we'll be consistent with real-world usage as well as gov-specific terminology.
- Conveniently, we don’t need to change the acronym (USWDS).

Moving forward as the U.S. Web Design System is the right thing to do and will strengthen the system going forward. Our mission to provide research-backed design patterns for building accessible, responsive, and consistent digital products for the federal government is as important as ever, and we're focused on improving what we do and the benefits we provide to those who use what we make.

We’d like to thank everyone for contributing their time and expertise to the discussion and your patience as we worked through this issue. We’ll begin rolling this out in the next few weeks (see the [task list](https://github.com/18F/web-design-standards/issues/2300#issuecomment-358077868)). We look forward to continuing to work together in the coming year. 

Thank you,

USWDS Core Team
Dan O. Williams, Maya Benari, John Donmoyer, Andrea Sigritz

P.S. If you’d like to see what we’re working on next, check out our [2018 Product roadmap](https://federalist-proxy.app.cloud.gov/preview/18f/web-design-standards-docs/update-roadmap/whats-new/product-roadmap/).

**Comment by evetsreklaw** [comment] 2018-01-17 21:31
Thanks for the effort on this. I was a fan of "standard", but I understand the need to adapt. Looking forward to system updates.

**Comment by maya** [comment] 2018-01-17 21:31
Closing this as we begin implementation in https://github.com/18F/web-design-standards/issues/2300#issuecomment-358077868. Thank you!

**Closed by maya** 2018-01-17 21:31 UTC
Labels: [Priority] Major, [Status] Help wanted, [Type] Communication

**Comment by bruce-usab** [comment] 2018-01-18 13:47
Thank you @bendygirl and @thisisdano.
