### ISSUE TITLE
prep 1.4 release

### ISSUE THREAD

**Issue by donjo** [18F/web-design-standards#2133] opened 2017-08-28 16:49 UTC
USWDS 1.4 will include a number of small visual design changes that will need to be documented in the release notes with before/after screenshots

**Comment by toolness** [comment] 2017-09-22 21:09
Ok, I'm trying to come up with a list of all the changes since our last release.

## Accessibility improvements

* The search button's submit text is now visible to screen readers on all viewport sizes (#2065).
* A number of accessibility improvements have been made to the fractal site (#2057, #2064).

## Visual changes

* Alerts now have a deeply saturated left border to help differentiate them from surrounding content (#2095). **TODO: Add before/after screenshot.**

* Buttons look different now (#2098).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

* The focus state looks different now (#2112). **TODO: Add a brief explanation of the change, with rationale and before/after screenshot, assuming we don't revert this (see below).**

* Dropdowns look different now (#2115).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

* A new `usa-input-optional` class has been added, and the form examples have been changed to use it instead of `usa-input-required` (#2116). **TODO: Add a brief explanation of the rationale of the change. Also, does this mean that `usa-input-required` is deprecated, since it's no longer used in any fractal components? We should let users know.**

* Checkboxes and radios look different now (#2117).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

* Labels look different now (#2118).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

* The footer has been visually revamped (#2130).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

* The header has been visually revamped (#2131).  **TODO: Add a brief explanation of the change, with rationale and before/after screenshot.**

## Other changes

* The footer example provided by documentation included an `<h3>` inside an `<address>`, which was not standard HTML. The `<h3>` has been moved outside the `<address>` (#2128).

## New features for core development

* A mechanism for testing for visual regressions has been added (#2067, #2129).

* The [aXe accessibility tool](https://www.deque.com/products/axe/) is now run on all fractal components during testing, to ensure that accessibility regressions don't occur.

## Concerns

* My biggest concern about releasing our current `develop` branch as the new 1.4 is #2142. Given that we have accessibility advocates in our community urging us to hold off on this particular change until we have more data to back up this change, do we want to revert it for 1.4?

* In https://github.com/18F/web-design-standards/pull/2130#pullrequestreview-59637200, @msecret mentioned that he wanted to "refactor the complex class hierarchies but that should happen as it's own task".  As far as I know, this hasn't been done yet.  Should it be done before we cut a new release, or should this particular change be held back from a new release until those refactorings are made? (In part, this has to do with the meaning of "refactoring" in this context; is it ultimately something that will affect USWDS users who are trying to upgrade, either now or in the future?)

* What do the visual refreshes mean for legacy HTML?  For example, will a legacy header's HTML still look OK with the new CSS?  I'm noticing, for example, that #2131 adds a new `usa-width-one-fourth` class and uses it in the `nav-primary` template--will legacy nav-primary HTML still look okay with the new CSS?

**Comment by toolness** [comment] 2017-09-28 20:26
Ok, closing this now, as #2151 supersedes it.

**Closed by toolness** 2017-09-28 20:26 UTC
