### ISSUE TITLE
Mobile responsive tables?

### ISSUE THREAD

**Issue by wslack** [18F/web-design-standards#954] opened 2016-01-13 03:16 UTC
Hi friends, when viewing a table with 4+ columns made with the standards, a mobile responsive "expand table" button yielded a unresponsive table.

I don't really know how to fix this - as a user, I'm ok scrolling around as long as I have a way to figure out where I am in the table. Maybe use something like the bubble effect on the Mac dock, expanding text in middle of screen but still showing the whole context?

Related issue: https://github.com/presidential-innovation-fellows/open-opportunity-data/issues/21

**Comment by maya** [comment] 2016-01-13 05:33
Duplicate of #896. 

@wslack feel free to add any feedback in that issue.

**Closed by maya** 2016-01-13 05:33 UTC

**Comment by wslack** [comment] 2016-01-13 05:56
Thanks, was on mobile and github search doesn't really search there...
