### ISSUE TITLE
[Side navigation] No 'view on github' link in header on iPhone 6 Safari 

### ISSUE THREAD

**Issue by JuliaWinn** [18F/web-design-standards#581] opened 2015-09-16 15:58 UTC
This link is not viewable on iOS, either in the horizontal or vertical view. This is on an iPhone 6. 

![image](https://cloud.githubusercontent.com/assets/821557/9910244/1741b026-5c6a-11e5-909c-f3cb0a951bb4.png)
![image](https://cloud.githubusercontent.com/assets/821557/9910254/24f6bd88-5c6a-11e5-9e92-365347d5d207.png)

**Comment by carodew** [comment] 2015-09-16 20:42
This also will be fixed when we implement the new header.

**Comment by maya** [comment] 2015-10-21 20:35
@carodew this is the new mobile header. 

<img width="385" alt="screen shot 2015-10-21 at 1 34 56 pm" src="https://cloud.githubusercontent.com/assets/5249443/10649379/a0c8f4d6-77f8-11e5-92f2-78822b6b6ceb.png">

We never added the "view on github" by design.

**Comment by juliaelman** [comment] 2016-05-20 16:01
This will be solved via an updated layout that @carodew and @ericadeahl have completed. 

Leaving open until that new layout is implemented - thanks!

**Comment by juliaelman** [comment] 2017-02-16 14:50
"View on GitHub" link appears when sidenav is open on mobile view. See screenshot below:

![screen shot 2017-02-16 at 9 49 35 am](https://cloud.githubusercontent.com/assets/955558/23025895/63421b08-f42d-11e6-90d6-82b5201bd1a4.png)

**Closed by juliaelman** 2017-02-16 14:50 UTC
Labels: [Priority] Minor, [Skill] Content, [Skill] Front end, [Skill] User Experience, [Skill] Visual Design, [Status] Backlog, [Type] Documentation, [Type] Enhancement
